accounts/urls.py
from django.urls import path 
from . import views 

app_name='accounts'

urlpatterns=[
    path('userRegister/',views.userRegister,name='userRegister'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('activate/<uid>/<token>/',views.activate,name='activate'),
    path('myAccount/',views.myAccount,name='myAccount'),

    #forgot_password
    path('forgot_password/',views.forgot_password,name='forgot_password'),
    path('reset_password/<uid>/<token>/',views.reset_password,name='reset_password'),
    path('password_reset_done/',views.password_reset_done,name='password_reset_done'),

  
]

customer/urls.py
from django.urls import path 
from . import views 

app_name='customer'

urlpatterns=[
    path('customerDashboard/',views.customerDashboard,name='customerDashboard'),
    path('cprofile/',views.cprofile,name='cprofile'),
]

myapp/urls.py
from django.urls import path 
from . import views 
app_name='myapp'
urlpatterns=[
    path('',views.index,name='index')
]

order/urls.py
from django.urls import path 
from . import views 
app_name='order'
urlpatterns=[
    path('place_order/',views.place_order,name='place_order'),
    path('handle_esewa/',views.handle_esewa,name='handle_esewa'),
    path('failed_handle_esewa/',views.failed_handle_esewa,name='failed_handle_esewa'),
    path('esewacredentials/',views.esewacredentials,name='esewa_credentials'),
    path('order_complete/',views.order_complete,name='order_complete'),
    path('update-order-status',views.update_order_status,name='update_order_status'),
    path('server-update-order-status',views.server_update_order_status,name='server_update_order_status'),
    path('order/pdf/<str:order_number>/',views.download_pdf,name='download_pdf'),

    path('orders/',views.order_list,name='order_list'),
    path('vendor_orders/',views.vendor_order_list,name='vendor_order_list'),
    path('vendor_orders/<str:order_number>/',views.vendor_order_detail,name='vendor_order_detail'),
    path('orders/<str:order_number>/',views.order_detail,name='order_detail'),

    path('earnings/', views.earnings_report, name='earnings_report'),
    path('refunds/',views.refunds,name='refunds'),
    path('refund_detail/<int:pk>/',views.refund_detail,name='refund_detail'),
    path('payouts/',views.vendor_payout,name='vendor_payout'),
    path('payouts_detail/<int:pk>/',views.vendor_payout_detail,name='vendor_payout_detail')
    

]

customer/models.py
from django.db import models

# Create your models here.

customer/views.py
from accounts.forms import UserInfoForm, UserProfileForm
from accounts.models import UserProfile
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import get_object_or_404, redirect, render
from order.models import OrderedFood
from vendor.views import checkCustomer


# Create your views here.
@login_required(login_url="accounts:login")
@user_passes_test(checkCustomer)
def customerDashboard(request):
    orders = OrderedFood.objects.filter(
        user=request.user, status__in=["pending", "accepted"]
    )
    context = {"orders": orders}
    return render(request, "customer/customerDashboard.html", context)


@login_required(login_url="accounts:login")
@user_passes_test(checkCustomer)
def cprofile(request):
    profile = get_object_or_404(UserProfile, user=request.user)
    if request.method == "POST":
        profile_form = UserProfileForm(request.POST, request.FILES, instance=profile)
        user_form = UserInfoForm(request.POST, instance=request.user)
        if profile_form.is_valid() and user_form.is_valid():
            profile_form.save()
            user_form.save()
            messages.success(request, "profile updated successfully")
            return redirect("customer:cprofile")

        else:
            context = {
                "profile_form": profile_form,
                "user_form": user_form,
                "profile": profile,
            }
            return render(request, "customer/cprofile.html", context)

    else:
        profile_form = UserProfileForm(instance=profile)
        user_form = UserInfoForm(instance=request.user)
        context = {
            "profile_form": profile_form,
            "user_form": user_form,
            "profile": profile,
        }
        return render(request, "customer/cprofile.html", context)

customer/templates/customer/c_sidebar.html
<div class="user-account-nav user-account-sidebar">
    <div class="user-nav-list">
        <ul>
            <li class="{% if '/customer/' == request.path%}active{% endif %}"><a
                    href="{% url 'customer:customerDashboard' %}"><i class="fa fa-tachometer"></i>Dashboard</a></li>
            <li class="{% if 'cprofile' in request.path %}active{% endif %}"><a href="{% url 'customer:cprofile' %}">
                <i class="fa fa-user-circle"></i>Profile Setting</a></li>
            <li class="{% if 'orders' in request.path %} active {% endif %}"><a href="{% url 'order:order_list'%}">
               <i class="fa fa-shopping-cart"></i> Orders</a></li>
            <li class="{% if 'refund' in request.path %} active {% endif %}"><a href="{% url 'order:refunds' %}"><i class="fa fa-undo"></i>refunds</a></li>



            <li><a class="logout-btn" href="{% url 'accounts:logout'%}"><i class="fa fa-sign-out"></i>Signout</a></li>
        </ul>
    </div>
</div>

customer/templates/customer/cover.html
{% load static %}
<div class="page-section restaurant-detail-image-section" style=" background: url({% if user.user_profile.cover_photo %}{{user.user_profile.cover_photo.url}}{% else %}{% static 'images/default-cover.png' %}{% endif %}) no-repeat scroll 0 0 / cover;">
    <!-- Container Start -->
    <div class="container">
        <!-- Row Start -->
        <div class="row">
            <!-- Column Start -->
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="company-info-detail">
                    <div class="company-info">
                        <div class="img-holder">
                            <figure>
                                <img  src="{% if user.user_profile.profile_picture %}{{ user.user_profile.profile_picture.url }}{% else %}{% static 'images/default-profile.png' %} {% endif %}" alt="">
                            </figure>
                        </div>

                        <div class="text-holder">
                            <span class="restaurant-title">{{user.first_name}} {{user.last_name}}</span>
                            <div class="text">
                                <i class="icon-phone"></i>
                                <p>{{user.phone_number}}</p>
                                <i class="icon-envelop"></i>
                                <p>{{user.email}}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Column End -->
        </div>
        <!-- Row End -->
    </div>
    <!-- Container End -->
</div>

customer/templates/customer/cprofile.html
{% extends 'myapp/base.html'%}
{% load static %}
{% block body %}

<div class="main-section">
    {% include 'customer/cover.html'%}
    <div class="page-section account-header buyer-logged-in">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    <!-- load the sidebar     -->
                    {% include 'customer/c_sidebar.html' %}
                </div>
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                            <h5 class="text-uppercase">Profile settings</h5>
                            <form action="{% url 'customer:cprofile'%}" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-fields-set">
                                    <ul>
                                        <li>
                                            <div class="row">
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="restaurant-info">
                                                        <div class="img-holder">
                                                            <ul class="foodbakery-gallery-holder">
                                                                <li class="gal-img">
                                                                    <div class="drag-list">
                                                                        <div class="item-thumb">
                                                                            <img class="thumbnail"
                                                                                src="{% if profile.profile_picture %}{{profile.profile_picture.url}}{% else %}{% static 'images/default-profile.png'%}{% endif %}"
                                                                                alt="">
                                                                        </div>
                                                                    </div>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <div class="text-holder">
                                                            <label>Update Logo</label>
                                                            <div class="upload-gallery">
                                                                {{profile_form.profile_picture}}
                                                            </div>
                                                            {% if profile_form.profile_picture.errors %}
                                                            <div class="text-danger">
                                                                {{ profile_form.profile_picture.errors }}
                                                            </div>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="restaurant-info">
                                                        <div class="img-holder">
                                                            <ul class="foodbakery-gallery-holder">
                                                                <li class="gal-img">
                                                                    <div class="drag-list">
                                                                        <div class="item-thumb">
                                                                            <img class="thumbnail"
                                                                                src="{% if profile.cover_photo %}{{profile.cover_photo.url}}{% else %}{% static 'images/default-cover.PNG'%}{% endif %}"
                                                                                alt="">
                                                                        </div>
                                                                    </div>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <div class="text-holder">
                                                            <label>Update Cover Photo</label>
                                                            <div class="upload-gallery">
                                                                {{profile_form.cover_photo}}
                                                            </div>
                                                            {% if profile_form.cover_photo.errors %}
                                                            <div class="text-danger">
                                                                {{ profile_form.cover_photo.errors }}
                                                            </div>
                                                            {% endif %}

                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="field-holder">
                                                        <label>First Name *</label>
                                                        {{user_form.first_name}}
                                                    </div>
                                                    {% if user_form.first_name.errors %}
                                                            <div class="text-danger">
                                                                {{ user_form.first_name.errors }}
                                                            </div>
                                                            {% endif %}
                                                </div>
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="field-holder">
                                                        <label>Last Name *</label>
                                                        {{user_form.last_name}}
                                                    </div>
                                                    {% if user_form.last_name.errors %}
                                                            <div class="text-danger">
                                                                {{ user_form.last_name.errors }}
                                                            </div>
                                                            {% endif %}
                                                </div>
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="field-holder">
                                                        <label>Phone Number *</label>
                                                        {{user_form.phone_number}}
                                                    </div>
                                                    {% if user_form.phone_number.errors %}
                                                            <div class="text-danger">
                                                                {{ user_form.phone_number.errors }}
                                                            </div>
                                                            {% endif %}
                                                </div>
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="field-holder">
                                                        <label>Address</label>
                                                        {{profile_form.address}}
                                                        <small class="text-muted float-right">powered by Google</small>
                                                    </div>
                                                </div>
                                                <div id="map"></div>

                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="field-holder">
                                                        <label>Country</label>
                                                        {{profile_form.country}}
                                                    </div>
                                                </div>
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="field-holder">
                                                        <label>State</label>
                                                        {{profile_form.state}}
                                                    </div>
                                                </div>
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="field-holder">
                                                        <label>pin_code</label>
                                                        {{profile_form.pin_code}}
                                                    </div>
                                                </div>
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="field-holder">
                                                        <label>Latitude</label>
                                                        {{profile_form.latitude}}
                                                    </div>
                                                </div>
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                    <div class="field-holder">
                                                        <label>Longitude</label>
                                                        {{profile_form.longitude}}
                                                    </div>
                                                </div>

                                            </div>
                                        </li>
                                    </ul>
                                    <div>
                                        <div class="field-holder">
                                            <div class="payment-holder input-button-loader">
                                                <input type="submit" value="Update you restaurnat">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>



                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

customer/templates/customer/customerDashboard.html
{% extends 'myapp/base.html'%}
{% load static %}
{% block body %}

<div class="main-section">
    {% include 'customer/cover.html' %}
    <div class="page-section account-header buyer-logged-in">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    <!-- load the sidebar -->
                    {% include 'customer/c_sidebar.html' %}
                </div>
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                            <h3 class="mb-4">My Orders</h3>
                            {% if orders %}
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th class="text-nowrap">Order ID</th>
                                            <th>Product</th>
                                            <th class="text-center">Qty</th>
                                            <th class="text-end">Price</th>
                                            <th class="text-center">Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for order in orders %}
                                        <tr data-order-id="{{order.id}}">
                                            <td class="text-nowrap">{{ order.id }}</td>
                                            <td class="text-truncate" style="max-width: 200px;" title="{{ order.fooditem.food_title }}">
                                                {{ order.fooditem.food_title }}
                                            </td>
                                            <td class="text-center">{{ order.quantity }}</td>
                                            <td class="text-end">Rs{{ order.amount }}</td>
                                            <td class="text-center">
                                                <span class="badge rounded-pill order-status 
                                                    {% if order.status == 'pending' %}text-bg-warning
                                                    {% elif order.status == 'cancelled' %}text-bg-danger
                                                    {% elif order.status == 'delivered' %}text-bg-success
                                                    {% else %}text-bg-primary{% endif %}">
                                                    {{ order.status|title }}
                                                </span>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            {% else %}
                            <div class="alert alert-info">You have no orders yet.</div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    /* Scoped styles that won't affect other pages */
    .user-holder table {
        width: 100%;
        font-size: 0.9rem;
    }
    
    .user-holder th {
        padding: 12px 8px;
        background-color: #f8f9fa;
    }
    
    .user-holder td {
        padding: 10px 8px;
        vertical-align: middle;
    }
    
    .user-holder .table-responsive {
        border-radius: 8px;
        overflow: hidden;
        box-shadow: 0 0 10px rgba(0,0,0,0.05);
    }
    
    .status-flash {
        animation: statusFlash 1s ease-out;
    }
    
    @keyframes statusFlash {
        0% { background-color: rgba(255, 235, 59, 0.3); }
        100% { background-color: transparent; }
    }
    
    .text-truncate {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }
</style>

<script>
document.addEventListener('DOMContentLoaded', function () {
    const orderSockets = {};
    const wsScheme = window.location.protocol === 'https:' ? 'wss' : 'ws';

    {% for order in orders %}
    (function (orderId) {
        const socket = new WebSocket(`${wsScheme}://foodonline.work.gd/ws/order/${orderId}/`);
        orderSockets[orderId] = socket;
        
        socket.onmessage = function (e) {
            const data = JSON.parse(e.data);
            const row = document.querySelector(`tr[data-order-id="${orderId}"]`);

            if (row) {
                const statusBadge = row.querySelector('.order-status');
                const statusColor = getStatusColor(data.status);
                statusBadge.className = `badge rounded-pill order-status ${statusColor}`;
                statusBadge.textContent = data.status;

                row.classList.add('status-flash');
                setTimeout(() => row.classList.remove('status-flash'), 1000);
            }
        };

        socket.onclose = function () {
            delete orderSockets[orderId];
        };

        socket.onerror = function (error) {
            console.error(`WebSocket Error for order ${orderId}:`, error);
        };
    })('{{ order.id }}');
    {% endfor %}

    window.addEventListener('beforeunload', () => {
        Object.values(orderSockets).forEach(socket => socket.close());
    });

    function getStatusColor(status) {
        const colors = {
            'pending': 'text-bg-warning',
            'accepted': 'text-bg-primary',
            'preparing': 'text-bg-info',
            'ready': 'text-bg-success',
            'delivered': 'text-bg-success',
            'cancelled': 'text-bg-danger'
        };
        return colors[status.toLowerCase()] || 'text-bg-secondary';
    }
});
</script>

{% endblock %}